In [1]:
from pathlib import Path
import pandas as pd

In [14]:
import parsers.samtools as fastqc
import csv
import os

In [10]:
with open(Path("/home/unicph.domain/glj523/samtools_file_list_examples.txt")) as f:
    files = [line.strip() for line in f if line.strip()]

In [ ]:
# First pass: collect all metrics to build column headers
metrics = []
print('collecting metrics')

filepath_metadata = files[0].split("/")


for filepath in files:
    with open(filepath) as f:
        for line in f:
            if line.startswith("SN\t"):
                metric = line.strip().split("\t")[1].rstrip(":")
                if metric not in metrics:
                    metrics.append(metric)

collecting metrics

In [ ]:
# Second pass: extract values per file
print('writing summary')
with open("summary.tsv", "w", newline="") as fout:
    writer = csv.writer(fout, delimiter="\t")
    writer.writerow(["filename"] + metrics)

    for filepath in files:
        row = {m: "" for m in metrics}
        with open(filepath) as f:
            for line in f:
                if line.startswith("SN\t"):
                    parts = line.strip().split("\t")
                    row[parts[1].rstrip(":")] = parts[2]
        writer.writerow([os.path.basename(filepath)] + [row[m] for m in metrics])

In [ ]:
filepath_metadata =

In [21]:
filepath

'/datasets/caeg_production/libraries/LV7/001/903/LV7001903372/20230414_BHMGMJDSX5/v1.0.8/4ebe3d1488023a26ec5b50b4e6a71f6b/stats/aligns/samtools_stats/Lib_LV7001903372_collapsed.txt'

In [26]:
filepath.split("/")[7]

'LV7001903372'

In [ ]:
filepath.split("/")[7] + filepath.split("/")[8].split("_") + filepath.split("/")[14:]

['LV7001903372', '20230414_BHMGMJDSX5', 'Lib_LV7001903372_collapsed.txt']

In [39]:
filepath

'/datasets/caeg_production/libraries/LV7/001/903/LV7001903372/20230414_BHMGMJDSX5/v1.0.8/4ebe3d1488023a26ec5b50b4e6a71f6b/stats/aligns/samtools_stats/Lib_LV7001903372_collapsed.txt'

In [35]:
filepath_metadata

['LV7001903372',
 '20230414_BHMGMJDSX5',
 'v1.0.8',
 '4ebe3d1488023a26ec5b50b4e6a71f6b',
 'Lib_LV7001903372_collapsed.txt']

In [15]:
os.path.basename(filepath)

'Lib_LV7001903372_collapsed.txt'

In [16]:
filepath.name

AttributeError: 'str' object has no attribute 'name'

In [ ]:
for filepath in files:
        row = {m: "" for m in metrics}
        with open(filepath) as f:
            for line in f:
                if line.startswith("SN\t"):
                    parts = line.strip().split("\t")
                    row[parts[1].rstrip(":")] = parts[2]

In [ ]:
for filepath in files:

In [6]:
merge_lanes['metadata']

{'FastQC_version': '0.12.1'}

In [8]:
merge_lanes['modules']['Basic Statistics']

{'status': 'pass',
 'header_values': {},
 'table': {'headers': ['Measure', 'Value'],
  'rows': [{'Measure': 'Filename',
    'Value': 'Lib_LV7008864206_collapsed.fastq.gz'},
   {'Measure': 'File type', 'Value': 'Conventional base calls'},
   {'Measure': 'Encoding', 'Value': 'Sanger / Illumina 1.9'},
   {'Measure': 'Total Sequences', 'Value': '188989298'},
   {'Measure': 'Total Bases', 'Value': '11 Gbp'},
   {'Measure': 'Sequences flagged as poor quality', 'Value': '0'},
   {'Measure': 'Sequence length', 'Value': '30-191'},
   {'Measure': '%GC', 'Value': '60'}]}}

In [36]:
def get_basic_stats(results) -> pd.DataFrame:
    combined_df = pd.DataFrame()
    for result in results:
        status_data = [{'Measure': f"{k} status", 'Value': v['status']} for k, v in result['modules'].items()]
        basic_stats = result['modules']['Basic Statistics']['table']['rows']
        header_data = [{'Measure': i, 'Value': j} for k, v in result['modules'].items() for i, j in v['header_values'].items()]
        df = pd.DataFrame(basic_stats + header_data + status_data)
        df = df.set_index('Measure').T.reset_index(drop=True)
        combined_df = pd.concat([combined_df, df], ignore_index=True)
    return combined_df

In [38]:
res

Measure,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status
0,Lib_LV7008864206_L001_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,46694974,2.7 Gbp,0,30-191,60,73.97223323811349,pass,pass,fail,pass,warn,fail,pass,warn,pass,pass,pass
1,Lib_LV7008864206_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,188989298,11 Gbp,0,30-191,60,44.66736217565382,pass,pass,fail,pass,warn,fail,pass,warn,fail,pass,pass

In [35]:
def combine_basic_stats(*results) -> pd.DataFrame:
    dfs = [get_basic_stats(result) for result in results]
    combined_df = pd.concat(dfs, ignore_index=True)
    return combined_df

In [34]:
res

Measure,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status
0,Lib_LV7008864206_L001_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,46694974,2.7 Gbp,0,30-191,60,73.97223323811349,pass,pass,fail,pass,warn,fail,pass,warn,pass,pass,pass

In [27]:
res

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,"{'Measure': 'Basic Statistics status', 'Value'...",{'Measure': 'Per base sequence quality status'...,{'Measure': 'Per tile sequence quality status'...,{'Measure': 'Per sequence quality scores statu...,{'Measure': 'Per base sequence content status'...,"{'Measure': 'Per sequence GC content status', ...","{'Measure': 'Per base N content status', 'Valu...",{'Measure': 'Sequence Length Distribution stat...,{'Measure': 'Sequence Duplication Levels statu...,{'Measure': 'Overrepresented sequences status'...,"{'Measure': 'Adapter Content status', 'Value':...","{'Measure': 'Filename', 'Value': 'Lib_LV700886...","{'Measure': 'File type', 'Value': 'Conventiona...","{'Measure': 'Encoding', 'Value': 'Sanger / Ill...","{'Measure': 'Total Sequences', 'Value': '18898...","{'Measure': 'Total Bases', 'Value': '11 Gbp'}",{'Measure': 'Sequences flagged as poor quality...,"{'Measure': 'Sequence length', 'Value': '30-191'}","{'Measure': '%GC', 'Value': '60'}","{'Measure': 'Total Deduplicated Percentage', '..."
1,"{'Measure': 'Basic Statistics status', 'Value'...",{'Measure': 'Per base sequence quality status'...,{'Measure': 'Per tile sequence quality status'...,{'Measure': 'Per sequence quality scores statu...,{'Measure': 'Per base sequence content status'...,"{'Measure': 'Per sequence GC content status', ...","{'Measure': 'Per base N content status', 'Valu...",{'Measure': 'Sequence Length Distribution stat...,{'Measure': 'Sequence Duplication Levels statu...,{'Measure': 'Overrepresented sequences status'...,"{'Measure': 'Adapter Content status', 'Value':...","{'Measure': 'Filename', 'Value': 'Lib_LV700886...","{'Measure': 'File type', 'Value': 'Conventiona...","{'Measure': 'Encoding', 'Value': 'Sanger / Ill...","{'Measure': 'Total Sequences', 'Value': '46694...","{'Measure': 'Total Bases', 'Value': '2.7 Gbp'}",{'Measure': 'Sequences flagged as poor quality...,"{'Measure': 'Sequence length', 'Value': '30-191'}","{'Measure': '%GC', 'Value': '60'}","{'Measure': 'Total Deduplicated Percentage', '..."

In [14]:
res

Measure,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage
0,pass,pass,fail,pass,warn,fail,pass,warn,fail,pass,pass,Lib_LV7008864206_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,188989298,11 Gbp,0,30-191,60,44.66736217565382

In [218]:
pd.concat([get_basic_stats(merge_lanes), get_basic_stats(trim_l1)])

Measure,Filename,File type,Encoding,Total Sequences,Total Bases,Sequences flagged as poor quality,Sequence length,%GC,Total Deduplicated Percentage,Basic Statistics status,Per base sequence quality status,Per tile sequence quality status,Per sequence quality scores status,Per base sequence content status,Per sequence GC content status,Per base N content status,Sequence Length Distribution status,Sequence Duplication Levels status,Overrepresented sequences status,Adapter Content status
0,Lib_LV7008864206_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,188989298,11 Gbp,0,30-191,60,73.97223323811349,pass,pass,fail,pass,warn,fail,pass,warn,fail,pass,pass
0,Lib_LV7008864206_L001_collapsed.fastq.gz,Conventional base calls,Sanger / Illumina 1.9,46694974,2.7 Gbp,0,30-191,60,73.97223323811349,pass,pass,fail,pass,warn,fail,pass,warn,pass,pass,pass